### ISSUE TITLE
shellcheck

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [jakwings/uuid.sh#1] opened 2022-04-30 22:45 UTC
[Line 79:](javascript:setPosition(79, 10))
  $DO_SH $DO_SH_OPTS ./uuid ${1+"$@"}
         ^-- [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([0])), apply [all SC2086](javascript:applyFixCode(2086)))
  $DO_SH "$DO_SH_OPTS" ./uuid ${1+"$@"}
 
[Line 82:](javascript:setPosition(82, 10))
  $DO_SH $DO_SH_OPTS ./uuid -s"${SEED}" ${1+"$@"}
         ^-- [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([1])), apply [all SC2086](javascript:applyFixCode(2086)))
  $DO_SH "$DO_SH_OPTS" ./uuid -s"${SEED}" ${1+"$@"}
 
[Line 86:](javascript:setPosition(86, 10))
  export PATH="${TESTPATH}"
         ^-- [SC2030](https://github.com/koalaman/shellcheck/wiki/SC2030) (info): Modification of PATH is local (to subshell caused by (..) group).
 
[Line 87:](javascript:setPosition(87, 10))
  $DO_SH $DO_SH_OPTS ./uuid -s"${SEED}" ${1+"$@"}
         ^-- [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([3])), apply [all SC2086](javascript:applyFixCode(2086)))
  $DO_SH "$DO_SH_OPTS" ./uuid -s"${SEED}" ${1+"$@"}
 
[Line 96:](javascript:setPosition(96, 10))
    if [ x"${checkname}" = x"$*" ]; then
         ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([4])), apply [all SC2268](javascript:applyFixCode(2268)))
    if [ "${checkname}" = "$*" ]; then
 
[Line 134:](javascript:setPosition(134, 29))
  IFS='-'; set -- "$1" "$2" $3; unset -v IFS
                            ^-- [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([5])), apply [all SC2086](javascript:applyFixCode(2086)))
  IFS='-'; set -- "$1" "$2" "$3"; unset -v IFS
 
[Line 139:](javascript:setPosition(139, 5))
  [ x"$1" = x"${5%???}" ]
    ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([6])), apply [all SC2268](javascript:applyFixCode(2268)))
  [ "$1" = "${5%???}" ]
 
[Line 285:](javascript:setPosition(285, 41))
checkpoint --binary v1; (set -e; export PATH="${TESTPATH}"; uuid_bs_test v1)
                                        ^-- [SC2030](https://github.com/koalaman/shellcheck/wiki/SC2030) (info): Modification of PATH is local (to subshell caused by (..) group).
                                        ^-- [SC2031](https://github.com/koalaman/shellcheck/wiki/SC2031) (info): PATH was modified in a subshell. That change might be lost.
 
[Line 290:](javascript:setPosition(290, 41))
checkpoint --binary v2; (set -e; export PATH="${TESTPATH}"; uuid_bs_test v2 7 6)
                                        ^-- [SC2030](https://github.com/koalaman/shellcheck/wiki/SC2030) (info): Modification of PATH is local (to subshell caused by (..) group).
                                        ^-- [SC2031](https://github.com/koalaman/shellcheck/wiki/SC2031) (info): PATH was modified in a subshell. That change might be lost.
 
[Line 295:](javascript:setPosition(295, 41))
checkpoint --binary v6; (set -e; export PATH="${TESTPATH}"; uuid_bs_test v6)
                                        ^-- [SC2030](https://github.com/koalaman/shellcheck/wiki/SC2030) (info): Modification of PATH is local (to subshell caused by (..) group).
                                        ^-- [SC2031](https://github.com/koalaman/shellcheck/wiki/SC2031) (info): PATH was modified in a subshell. That change might be lost.
 
[Line 301:](javascript:setPosition(301, 41))
checkpoint --binary v7; (set -e; export PATH="${TESTPATH}"; uuid_bs_test v7)
                                        ^-- [SC2030](https://github.com/koalaman/shellcheck/wiki/SC2030) (info): Modification of PATH is local (to subshell caused by (..) group).
                                        ^-- [SC2031](https://github.com/koalaman/shellcheck/wiki/SC2031) (info): PATH was modified in a subshell. That change might be lost.
 
[Line 310:](javascript:setPosition(310, 41))
checkpoint --binary v8; (set -e; export PATH="${TESTPATH}"; uuid_bs_test v8)
                                        ^-- [SC2031](https://github.com/koalaman/shellcheck/wiki/SC2031) (info): PATH was modified in a subshell. That change might be lost.
 
[Line 321:](javascript:setPosition(321, 5))
  [ x"${s1#?????????????????}" = x"${s2#?????????????????}" ]
    ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([16])), apply [all SC2268](javascript:applyFixCode(2268)))
  [ "${s1#?????????????????}" = "${s2#?????????????????}" ]
 
[Line 332:](javascript:setPosition(332, 7))
    [ x"${s1_1%"${s1_1#??}"}" = x"${s2_1#"${s2_1%??}"}" ]
      ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([17])), apply [all SC2268](javascript:applyFixCode(2268)))
    [ "${s1_1%"${s1_1#??}"}" = "${s2_1#"${s2_1%??}"}" ]
 
[Line 337:](javascript:setPosition(337, 7))
    [ x"${s1_2%"${s1_2#??}"}" = x"${s2_2#"${s2_2%??}"}" ]
      ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([18])), apply [all SC2268](javascript:applyFixCode(2268)))
    [ "${s1_2%"${s1_2#??}"}" = "${s2_2#"${s2_2%??}"}" ]
 
[Line 342:](javascript:setPosition(342, 7))
    [ x"${s1_3%"${s1_3#??}"}" = x"${s2_3#"${s2_3%??}"}" ]
      ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([19])), apply [all SC2268](javascript:applyFixCode(2268)))
    [ "${s1_3%"${s1_3#??}"}" = "${s2_3#"${s2_3%??}"}" ]
 
[Line 387:](javascript:setPosition(387, 7))
    [ x"${result}" = x"$(uuid -d "$1" $result)" ]
      ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                                      ^-- [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([20,21])), apply [all SC2086](javascript:applyFixCode(2086)), apply [all SC2268](javascript:applyFixCode(2268)))
    [ "${result}" = "$(uuid -d "$1" "$result")" ]
 
[Line 393:](javascript:setPosition(393, 5))
  [ x"${result}" = x"$(uuid_s -d "$1" $result)" ]
    ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                                      ^-- [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([22,23])), apply [all SC2086](javascript:applyFixCode(2086)), apply [all SC2268](javascript:applyFixCode(2268)))
  [ "${result}" = "$(uuid_s -d "$1" "$result")" ]
 
[Line 398:](javascript:setPosition(398, 5))
  [ x"${result}" = x"$(uuid_s v0 "${result}")" ]
    ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([24])), apply [all SC2268](javascript:applyFixCode(2268)))
  [ "${result}" = "$(uuid_s v0 "${result}")" ]
 
[Line 406:](javascript:setPosition(406, 17))
  [ "${ver}" = "${uuid_version}" ]
                ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_version is referenced but not assigned.
 
[Line 407:](javascript:setPosition(407, 17))
  [ "${var}" = "${uuid_variant}" ]
                ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_variant is referenced but not assigned.
 
[Line 410:](javascript:setPosition(410, 10))
  set -- $result
         ^-- [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.

Did you mean: ([apply this](javascript:applyFixIndex([27])), apply [all SC2086](javascript:applyFixCode(2086)))
  set -- "$result"
 
[Line 413:](javascript:setPosition(413, 9))
      [ x"$1" = x"${uuid_period}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_period is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([28])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$1" = "${uuid_period}" ]
 
[Line 414:](javascript:setPosition(414, 9))
      [ x"$2" = x"${uuid_sequence}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_sequence is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([30])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$2" = "${uuid_sequence}" ]
 
[Line 415:](javascript:setPosition(415, 9))
      [ x"$3" = x"${uuid_node}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_node is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([32])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$3" = "${uuid_node}" ]
 
[Line 418:](javascript:setPosition(418, 9))
      [ x"$1" = x"${uuid_domain}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_domain is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([34])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$1" = "${uuid_domain}" ]
 
[Line 419:](javascript:setPosition(419, 9))
      [ x"$2" = x"${uuid_identifier}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_identifier is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([36])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$2" = "${uuid_identifier}" ]
 
[Line 420:](javascript:setPosition(420, 9))
      [ x"$3" = x"${uuid_period}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([38])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$3" = "${uuid_period}" ]
 
[Line 421:](javascript:setPosition(421, 9))
      [ x"$4" = x"${uuid_sequence}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([39])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$4" = "${uuid_sequence}" ]
 
[Line 422:](javascript:setPosition(422, 9))
      [ x"$5" = x"${uuid_node}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([40])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$5" = "${uuid_node}" ]
 
[Line 425:](javascript:setPosition(425, 9))
      [ x"$1" = x"${uuid_second}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_second is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([41])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$1" = "${uuid_second}" ]
 
[Line 426:](javascript:setPosition(426, 9))
      [ x"$2" = x"${uuid_subsecond}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_subsecond is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([43])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$2" = "${uuid_subsecond}" ]
 
[Line 427:](javascript:setPosition(427, 9))
      [ x"$3" = x"${uuid_sequence}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([45])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$3" = "${uuid_sequence}" ]
 
[Line 428:](javascript:setPosition(428, 9))
      [ x"$4" = x"${uuid_node}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([46])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$4" = "${uuid_node}" ]
 
[Line 431:](javascript:setPosition(431, 9))
      [ x"$1" = x"${uuid_year}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_year is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([47])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$1" = "${uuid_year}" ]
 
[Line 432:](javascript:setPosition(432, 9))
      [ x"$2" = x"${uuid_month}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_month is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([49])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$2" = "${uuid_month}" ]
 
[Line 433:](javascript:setPosition(433, 9))
      [ x"$3" = x"${uuid_day}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_day is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([51])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$3" = "${uuid_day}" ]
 
[Line 434:](javascript:setPosition(434, 9))
      [ x"$4" = x"${uuid_hour}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_hour is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([53])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$4" = "${uuid_hour}" ]
 
[Line 435:](javascript:setPosition(435, 9))
      [ x"$5" = x"${uuid_minute}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.
                  ^-- [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154) (warning): uuid_minute is referenced but not assigned.

Did you mean: ([apply this](javascript:applyFixIndex([55])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$5" = "${uuid_minute}" ]
 
[Line 436:](javascript:setPosition(436, 9))
      [ x"$6" = x"${uuid_node}" ]
        ^-- [SC2268](https://github.com/koalaman/shellcheck/wiki/SC2268) (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: ([apply this](javascript:applyFixIndex([57])), apply [all SC2268](javascript:applyFixCode(2268)))
      [ "$6" = "${uuid_node}" ]

**Comment by iology** [comment] 2022-04-30 23:50
Hi, all those warnings have been explicitly disabled by the file `shellcheckrc` in this repo.

| shellcheckrc
:---------------
| disable=SC2030 disable=SC2031<br>(info): Modification of PATH is local (to subshell caused by (..) group).<br>(info): PATH was modified in a subshell. That change might be lost.
| Right.  You can see those commands are explicitly wrapped in `(...)`.
| disable=SC2086<br>(info): Double quote to prevent globbing and word splitting.
| That's the wanted result.  `unset -v IFS` is right at the top of the script for intended behavior.
| disable=SC2154<br>(warning): `uuid_*` is referenced but not assigned.
| Intended behavior (dynamic scoping).  `set -euf` at the start of the script will make reference to undefined variable to terminate the program.
| disable=SC2268<br>(style): Avoid x-prefix in comparisons as it no longer serves a purpose.
| I'm a bit paranoid here but it won't hurt.  shellcheck with the default config is more paranoid than me. ;)

Closing this issue :)

**Closed** 2022-04-30 23:51 UTC
